[package]
rust-version.workspace = true
name = "sdkwork-discovery-config"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-discovery-contract.workspace = true
sdkwork-utils-rust.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
