[package]
rust-version.workspace = true
name = "sdkwork-discovery-rpc"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-discovery-contract.workspace = true
sdkwork-discovery-core.workspace = true
sdkwork-discovery-rpc-proto.workspace = true
sdkwork-discovery-storage-contract.workspace = true
metrics.workspace = true
prost-types.workspace = true
sdkwork-utils-rust.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
sdkwork-discovery-health-checker.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
sdkwork-discovery-storage-memory.workspace = true
