[package]
rust-version.workspace = true
name = "sdkwork-discovery-storage-postgres"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
sdkwork-discovery-storage-contract.workspace = true
sdkwork-discovery-config.workspace = true
sdkwork-discovery-contract.workspace = true
sdkwork-discovery-database-host.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-sqlx.workspace = true
serde_json.workspace = true
sdkwork-utils-rust.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
