[package]
rust-version.workspace = true
name = "sdkwork-discovery-health-checker"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-discovery-contract.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["net", "time"] }
tonic = { workspace = true }
tonic-health = { workspace = true }
tracing.workspace = true
