[package]
rust-version.workspace = true
name = "sdkwork-discovery-service-host"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-discovery-contract.workspace = true
sdkwork-discovery-config.workspace = true
sdkwork-discovery-core.workspace = true
sdkwork-discovery-rpc.workspace = true
sdkwork-discovery-storage-contract.workspace = true
sdkwork-discovery-storage-memory.workspace = true
sdkwork-discovery-storage-postgres.workspace = true
sdkwork-discovery-storage-redis.workspace = true
axum.workspace = true
metrics.workspace = true
metrics-exporter-prometheus = { workspace = true, optional = true }
sdkwork-web-bootstrap.workspace = true
tokio = { workspace = true, features = ["signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
default = ["prometheus"]
prometheus = ["metrics-exporter-prometheus"]

[dev-dependencies]
sdkwork-discovery-rpc-proto.workspace = true
tonic.workspace = true
