-- SDKWork discovery consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_discovery_baseline.sql
-- Consolidated legacy SQLite baseline imported from sdkwork-discovery-storage-sqlite migrations
-- Review and replace with contract-first migrations.

-- source: crates/sdkwork-discovery-storage-sqlite/migrations/202606090001_initial_discovery_sqlite_schema.sql
CREATE TABLE IF NOT EXISTS discovery_revision_counter (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    namespace TEXT NOT NULL,
    environment TEXT NOT NULL,
    current_revision INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_revision_counter_scope UNIQUE (namespace, environment),
    CONSTRAINT uk_discovery_revision_counter_uuid UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS discovery_service_instance (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    namespace TEXT NOT NULL,
    environment TEXT NOT NULL,
    service_name TEXT NOT NULL,
    instance_id TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    protocol TEXT NOT NULL,
    service_version TEXT NOT NULL,
    region TEXT NOT NULL,
    zone TEXT NOT NULL,
    weight INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    status TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    lease_id TEXT NOT NULL,
    expires_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL,
    health_check_json TEXT,
    health_check_state_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_service_instance_identity UNIQUE (namespace, environment, service_name, instance_id),
    CONSTRAINT uk_discovery_service_instance_lease UNIQUE (lease_id),
    CONSTRAINT uk_discovery_service_instance_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_discovery_service_instance_discover
    ON discovery_service_instance (namespace, environment, service_name, protocol, status, expires_at_ms);

CREATE INDEX IF NOT EXISTS idx_discovery_service_instance_expiry
    ON discovery_service_instance (expires_at_ms, namespace, environment, service_name, instance_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS discovery_config_draft (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    draft_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    environment TEXT NOT NULL,
    config_group TEXT NOT NULL,
    config_key TEXT NOT NULL,
    config_format TEXT NOT NULL,
    config_value TEXT NOT NULL,
    scope_kind TEXT NOT NULL,
    scope_application TEXT,
    scope_service_name TEXT,
    created_by TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    published INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_config_draft_id UNIQUE (draft_id),
    CONSTRAINT uk_discovery_config_draft_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_discovery_config_draft_scope
    ON discovery_config_draft (namespace, environment, config_group, config_key, scope_kind);

CREATE TABLE IF NOT EXISTS discovery_config_release (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    release_id TEXT NOT NULL,
    draft_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    environment TEXT NOT NULL,
    config_group TEXT NOT NULL,
    config_key TEXT NOT NULL,
    config_format TEXT NOT NULL,
    config_value TEXT NOT NULL,
    scope_kind TEXT NOT NULL,
    scope_application TEXT,
    scope_service_name TEXT,
    content_hash TEXT NOT NULL,
    published_by TEXT NOT NULL,
    published_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_config_release_id UNIQUE (release_id),
    CONSTRAINT uk_discovery_config_release_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_discovery_config_release_effective
    ON discovery_config_release (namespace, environment, config_group, config_key, scope_kind, revision);

CREATE TABLE IF NOT EXISTS discovery_idempotency_record (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    operation_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    resource_kind TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_idempotency_record_identity UNIQUE (operation_id, idempotency_key),
    CONSTRAINT uk_discovery_idempotency_record_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_discovery_idempotency_record_resource
    ON discovery_idempotency_record (resource_kind, resource_id);

CREATE TABLE IF NOT EXISTS discovery_watch_event (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    revision INTEGER NOT NULL,
    namespace TEXT NOT NULL,
    environment TEXT NOT NULL,
    event_kind TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    config_application TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    deleted_at TEXT,
    CONSTRAINT uk_discovery_watch_event_scope_revision UNIQUE (namespace, environment, revision),
    CONSTRAINT uk_discovery_watch_event_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_discovery_watch_event_scope_revision
    ON discovery_watch_event (namespace, environment, revision);
