[package]
rust-version.workspace = true
name = "sdkwork-discovery-core"
edition.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
serde_json.workspace = true
sdkwork-discovery-contract.workspace = true
sdkwork-discovery-storage-contract.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
sdkwork-discovery-storage-memory.workspace = true
tokio.workspace = true
